# 配置文件

DAILY_TIME: "23:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2020-09-17" # 纪念日
CITY: "湖南"

BIRTHDAY:
  - "08-22"

APP_ID: "
wx3ffab4b3b6786621"
APP_SECRET: "5ee7872f77f26b0e33d0f9a11a77268d"

USER_ID: 
  - "oVTRn62ikCDzC8dZarZ3YsL0l7dE"
  - "oVTRn6wibjwnVIqnwyMMxPMiWlRE" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "	sbjSbRNweUOa1PFG0qFvIPgn_Fb_FQv04Rbu7dtVc58"
